### ISSUE TITLE
Do you train the generative model on retrieved source code?

### ISSUE THREAD

**Issue by wasiahmad** [microsoft/ReACC#3]
The readme part of [generation](https://github.com/microsoft/ReACC#4-generation-step) only talks about inference. Do you train the generative model (codegpt-adapted) with retrieved code? Or, you just evaluate off-the-shelf codegpt-adapted by augmenting the input with retrieved code at the inference step?

**Comment by celbree** [comment]
No, we **didn't** fine-tune the generative model (codegpt-adapted) **with retrieved code**. But we have fine-tuned it on PY150 dataset for normal code completion.

**Comment by wasiahmad** [comment]
So, to confirm, the generative models only observed the input and output sequences. In no way, the model did observe any retrieved code during training? 

Just curious, because the model didn't observe inputs as `retrieved completion + input` during training, how does it effectively utilize the retrieved code for code completion during inference?

**Comment by celbree** [comment]
You're right. The model did **NOT** see any retrieved code during training. I think the retrieved code could be considered as a relevant context since it is common in some codes that there exist similar function implementations before the current writing function. However, we are not sure if training with retrieved code can bring more improvements as we didn't do experiments on this.
